import { I18nProvider } from "@/components/elements/i18n-provider";
import { Providers } from "@/components/elements/providers";
import { ThemeProvider } from "@/components/elements/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { defaultLocale } from "@/lib/i18n/config";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
	weight: ["400", "500", "700"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata = {
	title: "Organizze",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		// `lang` is kept in sync with the active locale by <I18nProvider>.
		<html lang={defaultLocale} suppressHydrationWarning>
			<body className={rubik.className}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<I18nProvider>
						<Providers>
							{children}
							<Toaster richColors position="top-right" />
						</Providers>
					</I18nProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
